name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']

    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        uses: actions/setup-go@v2
        run: |
            python -m pip install -r development.txt
            python setup.py install
      - name: Test
        run: |
            make test