name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.5']

    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade -r development.txt
      - name: Build wheel
        run: |
          go get -d
          type python
          python setup.py bdist_wheel
          pip install dist/pybluemonday*.whl
      - name: Test
        # For some reason .so's being built aren't working and I have no idea why.
        # Let python use the wheel that we installed above by deleting the module in the folder
        run: |
            rm -rf pybluemonday/
            make test
