name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python-version: ['3.6']

    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
            python -m pip install -r development.txt
            python -m pip install .
      - name: Test
        # For some reason .so's being built aren't working and I have no idea why.
        # Let python use the wheel that we installed above by deleting the module in the folder
        run: |
            rm -rf pybluemonday/
            make test
