name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.6']

    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
            python -m pip install -r development.txt
            go get -d
            make clean
            make so
            make ffi
            mv bluemonday.*.so pybluemonday/
      - uses: mxschmitt/action-tmate@v3
      # - name: Test
      #   run: |
      #       make test
